------------------------------------------------------------------------------------------------------------------
------------------------------------------------------ INIT ------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

/*Para seleccionar la BD por defecto*/
USE [GD2C2023]
GO

/*Crear el schema con el nombre del grupo*/
/*CREATE SCHEMA [MMMD]
GO*/
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'MMMD')
BEGIN 
	EXEC ('CREATE SCHEMA MMMD')
END
GO

------------------------------------------------------------------------------------------------------------------
----------------------------------------------------- TABLAS -----------------------------------------------------
------------------------------------------------------------------------------------------------------------------

CREATE TABLE [MMMD].[Agente] (
	[AGENTE_CODIGO] numeric(19, 0) NOT NULL IDENTITY PRIMARY KEY,
	[AGENTE_NOMBRE] nvarchar(100) NULL,
	[AGENTE_APELLIDO] nvarchar(100) NULL,
	[AGENTE_DNI] numeric(18, 0) NULL,
	[AGENTE_FECHA_REGISTRO] datetime NULL,
	[AGENTE_TELEFONO] numeric(18, 0) NULL,
	[AGENTE_MAIL] nvarchar(100) NULL,
	[AGENTE_FECHA_NAC] datetime NULL,

	[AGENTE_SUCURSAL_CODIGO] numeric(18, 0) NULL,
)
GO

CREATE TABLE [MMMD].[Sucursal] (
	[SUCURSAL_CODIGO] numeric(18, 0) NOT NULL PRIMARY KEY,
	[SUCURSAL_NOMBRE] nvarchar(100) NULL,
	[SUCURSAL_DIRECCION] nvarchar(100) NULL,
	[SUCURSAL_TELEFONO] nvarchar(100) NULL,

	[SUCURSAL_LOCALIDAD_CODIGO] numeric(18, 0) NULL,
)
GO

CREATE TABLE [MMMD].[Localidad] (
	[LOCALIDAD_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[LOCALIDAD_NOMBRE] nvarchar(100) NULL,

	[LOCALIDAD_PROVINCIA_CODIGO] numeric(18, 0) NULL,
)
GO

CREATE TABLE [MMMD].[Provincia] (
	[PROVINCIA_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[PROVINCIA_NOMBRE] nvarchar(100) NULL,
)
GO

CREATE TABLE [MMMD].[Barrio] (
	[BARRIO_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[BARRIO_NOMBRE] nvarchar(100) NULL,

	[BARRIO_LOCALIDAD_CODIGO] numeric(18, 0) NULL,
)
GO

CREATE TABLE [MMMD].[Anuncio] (
	[ANUNCIO_CODIGO] numeric(19, 0) NOT NULL PRIMARY KEY,
	[ANUNCIO_FECHA_PUBLICACION] datetime NULL,
	[ANUNCIO_PRECIO_PUBLICADO] numeric(18, 2) NULL,
	[ANUNCIO_COSTO_ANUNCIO] numeric(18, 2) NULL,
	[ANUNCIO_FECHA_FINALIZACION] datetime NULL,

	[ANUNCIO_TIPO_OPERACION] numeric(18, 0) NULL,
	[ANUNCIO_MONEDA] numeric(18, 0) NULL,
	[ANUNCIO_ESTADO] numeric(18, 0) NULL,
	[ANUNCIO_TIPO_PERIODO] numeric(18, 0) NULL,
	[ANUNCIO_AGENTE_CODIGO] numeric(19, 0) NULL,
	[ANUNCIO_INMUEBLE_CODIGO] numeric(18, 0) NULL,
)
GO

CREATE TABLE [MMMD].[TipoOperacion] (
	[OP_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[OP_NOMBRE] nvarchar(100) NULL,
)
GO

CREATE TABLE [MMMD].[Moneda] (
	[MONEDA_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[MONEDA_NOMBRE] nvarchar(100) NULL,
)
GO

CREATE TABLE [MMMD].[EstadoAnuncio] (
	[ESTADO_ANUNCIO_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[ESTADO_ANUNCIO_NOMBRE] nvarchar(100) NULL,
)
GO

CREATE TABLE [MMMD].[TipoPeriodo] (
	[TIPO_PERIODO_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[TIPO_PERIODO_NOMBRE] nvarchar(100) NULL,
)
GO

CREATE TABLE [MMMD].[Inmueble] (
	[INMUEBLE_CODIGO] numeric(18, 0) NOT NULL PRIMARY KEY,
	[INMUEBLE_NOMBRE] nvarchar(100) NULL,
	[INMUEBLE_DESCRIPCION] nvarchar(100) NULL,
	[INMUEBLE_DIRECCION] nvarchar(100) NULL,
	[INMUEBLE_SUPERFICIETOTAL] numeric(18, 2) NULL,
	[INMUEBLE_ANTIGUEDAD] numeric(18, 0) NULL,
	[INMUEBLE_EXPESAS] numeric(18, 2) NULL,
	[INMUEBLE_ORIENTACION] nvarchar(100) NULL,

	[INMUEBLE_BARRIO] numeric(18, 0) NULL,
	[INMUEBLE_TIPO_INMUEBLE] numeric(18, 0) NULL,
	[INMUEBLE_CANT_AMBIENTES] numeric(18, 0) NULL,
	[INMUEBLE_DISPOSICION] numeric(18, 0) NULL,
	[INMUEBLE_ESTADO] numeric(18, 0) NULL,
	[INMUEBLE_PROPIETARIO_CODIGO] numeric(18, 0) NULL,
)
GO

CREATE TABLE [MMMD].[CaracteristicaBase] (
	[CARACTERISTICA_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[CARACTERISTICA_NOMBRE] nvarchar(100) NULL,
)
GO

CREATE TABLE [MMMD].[CaracteristicaPorInmueble] (
	[CARACTERISTICA_CODIGO] numeric(18, 0) NOT NULL,
	[INMUEBLE_CODIGO] numeric(18, 0) NOT NULL,
	CONSTRAINT PK_CaracteristicaPorInmueble PRIMARY KEY ([CARACTERISTICA_CODIGO], [INMUEBLE_CODIGO])
)
GO

CREATE TABLE [MMMD].[TipoInmueble] (
	[TIPOINMUEBLE_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[TIPOINMUEBLE_NOMBRE] nvarchar(100) NULL,
)
GO

CREATE TABLE [MMMD].[CantidadAmbientes] (
	[AMBIENTES_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[AMBIENTES_NOMBRE] nvarchar(100) NULL,
)
GO

CREATE TABLE [MMMD].[DisposicionInmueble] (
	[DISPOSICION_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[DISPOSICION_NOMBRE] nvarchar(100) NULL,
)
GO

CREATE TABLE [MMMD].[EstadoInmueble] (
	[ESTADO_INMUEBLE_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[ESTADO_INMUEBLE_NOMBRE] nvarchar(100) NULL,
)
GO

CREATE TABLE [MMMD].[Propietario] (
	[PROPIETARIO_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[PROPIETARIO_NOMBRE] nvarchar(100) NULL,
	[PROPIETARIO_APELLIDO] nvarchar(100) NULL,
	[PROPIETARIO_DNI] numeric(18, 0) NULL,
	[PROPIETARIO_FECHA_REGISTRO] datetime NULL,
	[PROPIETARIO_TELEFONO] numeric(18, 0) NULL,
	[PROPIETARIO_MAIL] nvarchar(255) NULL,
	[PROPIETARIO_FECHA_NAC] datetime NULL,
)
GO

CREATE TABLE [MMMD].[Venta] (
	[VENTA_CODIGO] numeric(18, 0) NOT NULL PRIMARY KEY,
	[VENTA_FECHA] datetime NULL,
	[VENTA_PRECIO_VENTA] numeric(18, 2) NULL,
	[VENTA_COMISION] numeric(18, 2) NULL,

	[VENTA_MONEDA] numeric(18, 0) NULL,
	[VENTA_ANUNCIO_CODIGO] numeric(19, 0) NULL,
	[VENTA_COMPRADOR_CODIGO] numeric(18, 0) NULL,
)
GO

CREATE TABLE [MMMD].[Comprador] (
	[COMPRADOR_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[COMPRADOR_NOMBRE] nvarchar(100) NULL,
	[COMPRADOR_APELLIDO] nvarchar(100) NULL,
	[COMPRADOR_DNI] numeric(18, 0) NULL,
	[COMPRADOR_FECHA_REGISTRO] datetime NULL,
	[COMPRADOR_TELEFONO] numeric(18, 0) NULL,
	[COMPRADOR_MAIL] nvarchar(100) NULL,
	[COMPRADOR_FECHA_NAC] datetime NULL,
)
GO

CREATE TABLE [MMMD].[PagoVenta] (
	[PAGO_VENTA_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[PAGO_VENTA_IMPORTE] numeric(18, 2) NULL,
	[PAGO_VENTA_COTIZACION] numeric(18, 2) NULL,
	
	[PAGO_VENTA_VENTA_CODIGO] numeric(18, 0) NULL,
	[PAGO_VENTA_MONEDA] numeric(18, 0) NULL,
	[PAGO_VENTA_MEDIO_PAGO] numeric(18, 0) NULL,
)
GO

CREATE TABLE [MMMD].[MedioDePago] (
	[MEDIO_PAGO_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[MEDIO_PAGO_NOMBRE] nvarchar(100) NULL,
)
GO

CREATE TABLE [MMMD].[Alquiler] (
	[ALQUILER_CODIGO] numeric(18, 0) NOT NULL PRIMARY KEY,
	[ALQUILER_FECHA_INICIO] datetime NULL,
	[ALQUILER_FECHA_FIN] datetime NULL,
	[ALQUILER_CANT_PERIODOS] numeric(18, 0) NULL,
	[ALQUILER_DEPOSITO] numeric(18, 2) NULL,
	[ALQUILER_COMISION] numeric(18, 2) NULL,
	[ALQUILER_GASTOS_AVERIGUA] numeric(18, 2) NULL,
	
	[ALQUILER_ANUNCIO_CODIGO] numeric(19, 0) NULL,
	[ALQUILER_INQUILINO_CODIGO] numeric(18, 0) NULL,
	[ALQUILER_ESTADO] numeric(18, 0) NULL,
)
GO

CREATE TABLE [MMMD].[Inquilino] (
	[INQUILINO_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[INQUILINO_NOMBRE] nvarchar(100) NULL,
	[INQUILINO_APELLIDO] nvarchar(100) NULL,
	[INQUILINO_DNI] numeric(18, 0) NULL,
	[INQUILINO_FECHA_REGISTRO] datetime NULL,
	[INQUILINO_TELEFONO] numeric(18, 0) NULL,
	[INQUILINO_MAIL] nvarchar(100) NULL,
	[INQUILINO_FECHA_NAC] datetime NULL,
)
GO

CREATE TABLE [MMMD].[EstadoAlquiler] (
	[ESTADO_ALQUILER_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[ESTADO_ALQUILER_NOMBRE] nvarchar(100) NULL,
)
GO

CREATE TABLE [MMMD].[DetalleAlq] (
	[DETALLE_ALQ_CODIGO] numeric(18, 0) NOT NULL IDENTITY PRIMARY KEY,
	[DETALLE_ALQ_NRO_PERIODO_INI] numeric(18, 0) NULL,
	[DETALLE_ALQ_NRO_PERIODO_FIN] numeric(18, 0) NULL,
	[DETALLE_ALQ_PRECIO] numeric(18, 2) NULL,
	
	[DETALLE_ALQ_ALQUILER_CODIGO] numeric(18, 0) NULL,
)
GO

CREATE TABLE [MMMD].[PagoAlquiler] (
	[PAGO_ALQUILER_CODIGO] numeric(18, 0) NOT NULL PRIMARY KEY,
	[PAGO_ALQUILER_FECHA] datetime NULL,
	[PAGO_ALQUILER_FECHA_VENCIMIENTO] datetime NULL,
	[PAGO_ALQUILER_NRO_PERIODO] numeric(18, 0) NULL,
	[PAGO_ALQUILER_DESC] nvarchar(100) NULL,
	[PAGO_ALQUILER_FEC_INI] datetime NULL,
	[PAGO_ALQUILER_FEC_FIN] datetime NULL,
	[PAGO_ALQUILER_IMPORTE] numeric(18, 2) NULL,
	
	[PAGO_ALQUILER_ALQUILER_CODIGO] numeric(18, 0) NULL,
	[PAGO_ALQUILER_MEDIO_PAGO] numeric(18, 0) NULL,
)
GO

----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------- PROCEDURES -----------------------------------------------------
----------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE MMMD.Migrar_Comprador AS
BEGIN
	INSERT INTO MMMD.Comprador
		(COMPRADOR_NOMBRE, 
		COMPRADOR_APELLIDO, 
		COMPRADOR_DNI, 
		COMPRADOR_FECHA_REGISTRO,	
		COMPRADOR_TELEFONO,	
		COMPRADOR_MAIL,	
		COMPRADOR_FECHA_NAC)
	SELECT DISTINCT
		m.COMPRADOR_NOMBRE,
		m.COMPRADOR_APELLIDO,
		m.COMPRADOR_DNI,
		m.COMPRADOR_FECHA_REGISTRO,
		m.COMPRADOR_TELEFONO,
		m.COMPRADOR_MAIL,
		m.COMPRADOR_FECHA_NAC
	FROM gd_esquema.Maestra m
	WHERE m.COMPRADOR_APELLIDO IS NOT NULL
END
GO

CREATE PROCEDURE MMMD.Migrar_Moneda AS
BEGIN
	INSERT INTO MMMD.Moneda
	SELECT DISTINCT
		m.ANUNCIO_MONEDA	--DEBERIA HABER UN UNION CON VENTA_MONEDA Y PAGO_VENTA_MONEDA
	FROM gd_esquema.Maestra m
	WHERE m.ANUNCIO_MONEDA IS NOT NULL
END
GO

CREATE PROCEDURE MMMD.Migrar_MedioDePago AS
BEGIN
	INSERT INTO MMMD.MedioDePago
	SELECT DISTINCT
		m.PAGO_ALQUILER_MEDIO_PAGO	--DEBERIA HABER UN UNION CON PAGO_VENTA_MEDIO_PAGO
	FROM gd_esquema.Maestra m
	WHERE m.PAGO_ALQUILER_MEDIO_PAGO IS NOT NULL
END
GO

CREATE PROCEDURE MMMD.Migrar_Propietario AS
BEGIN
	INSERT INTO MMMD.Propietario 
		(PROPIETARIO_NOMBRE, 
		PROPIETARIO_APELLIDO, 
		PROPIETARIO_DNI, 
		PROPIETARIO_FECHA_REGISTRO, 
		PROPIETARIO_TELEFONO, 
		PROPIETARIO_MAIL, 
		PROPIETARIO_FECHA_NAC)
	SELECT DISTINCT
		m.PROPIETARIO_NOMBRE,
		m.PROPIETARIO_APELLIDO,
		m.PROPIETARIO_DNI,
		m.PROPIETARIO_FECHA_REGISTRO,
		m.PROPIETARIO_TELEFONO,
		m.PROPIETARIO_MAIL,	
		m.PROPIETARIO_FECHA_NAC
	FROM gd_esquema.Maestra m
	WHERE m.PROPIETARIO_APELLIDO IS NOT NULL
END
GO

CREATE PROCEDURE MMMD.Migrar_Provincia AS
BEGIN
	INSERT INTO MMMD.Provincia 
		(PROVINCIA_NOMBRE)
	SELECT DISTINCT
		m.SUCURSAL_PROVINCIA 
	FROM gd_esquema.Maestra m
	WHERE m.SUCURSAL_PROVINCIA IS NOT NULL
	UNION
	SELECT DISTINCT
		m.INMUEBLE_PROVINCIA
	FROM gd_esquema.Maestra m
	WHERE m.INMUEBLE_PROVINCIA IS NOT NULL
END
GO

CREATE PROCEDURE MMMD.Migrar_Localidad AS
BEGIN
	INSERT INTO MMMD.Localidad 
		(LOCALIDAD_NOMBRE, 
		LOCALIDAD_PROVINCIA_CODIGO)
	SELECT DISTINCT
		m.SUCURSAL_LOCALIDAD,
		P.PROVINCIA_CODIGO
	FROM gd_esquema.Maestra m
	JOIN MMMD.Provincia	P ON P.PROVINCIA_NOMBRE = m.SUCURSAL_PROVINCIA
	WHERE m.SUCURSAL_LOCALIDAD IS NOT NULL
	UNION
	SELECT DISTINCT
		m.INMUEBLE_LOCALIDAD,
		P.PROVINCIA_CODIGO
	FROM gd_esquema.Maestra m
	JOIN MMMD.Provincia	P ON P.PROVINCIA_NOMBRE = m.INMUEBLE_PROVINCIA
	WHERE m.INMUEBLE_LOCALIDAD IS NOT NULL
END
GO

CREATE PROCEDURE MMMD.Migrar_Barrio AS
BEGIN
	INSERT INTO MMMD.Barrio 
		(BARRIO_NOMBRE, 
		BARRIO_LOCALIDAD_CODIGO)
	SELECT DISTINCT
		m.INMUEBLE_BARRIO,
		L.LOCALIDAD_CODIGO
	FROM gd_esquema.Maestra m
	JOIN MMMD.Localidad	L ON L.LOCALIDAD_NOMBRE = m.INMUEBLE_LOCALIDAD
	WHERE m.INMUEBLE_BARRIO IS NOT NULL
END
GO

CREATE PROCEDURE MMMD.Migrar_Sucursal AS
BEGIN
	INSERT INTO MMMD.Sucursal 
		(SUCURSAL_CODIGO, 
		SUCURSAL_NOMBRE, 
		SUCURSAL_DIRECCION, 
		SUCURSAL_TELEFONO, 
		SUCURSAL_LOCALIDAD_CODIGO)
	SELECT DISTINCT
		m.SUCURSAL_CODIGO, 
		m.SUCURSAL_NOMBRE, 
		m.SUCURSAL_DIRECCION, 
		m.SUCURSAL_TELEFONO, 
		L.LOCALIDAD_CODIGO
	FROM gd_esquema.Maestra m
	JOIN MMMD.Localidad	L ON L.LOCALIDAD_NOMBRE = m.SUCURSAL_LOCALIDAD
	WHERE m.SUCURSAL_CODIGO IS NOT NULL
END
GO

CREATE PROCEDURE MMMD.Migrar_Agente AS
BEGIN
	INSERT INTO MMMD.Agente
		(AGENTE_NOMBRE,
		AGENTE_APELLIDO,
		AGENTE_DNI,
		AGENTE_FECHA_REGISTRO,
		AGENTE_TELEFONO,
		AGENTE_MAIL,
		AGENTE_FECHA_NAC,
		AGENTE_SUCURSAL_CODIGO)
	SELECT DISTINCT
		m.AGENTE_NOMBRE,
		m.AGENTE_APELLIDO,
		m.AGENTE_DNI,
		m.AGENTE_FECHA_REGISTRO,
		m.AGENTE_TELEFONO,
		m.AGENTE_MAIL,
		m.AGENTE_FECHA_NAC,
		S.SUCURSAL_CODIGO
	FROM gd_esquema.Maestra m
	JOIN MMMD.Sucursal S ON S.SUCURSAL_NOMBRE = m.SUCURSAL_NOMBRE
	WHERE m.AGENTE_DNI IS NOT NULL
END
GO

CREATE PROCEDURE MMMD.Migrar_DetalleAlq AS
BEGIN 
	INSERT INTO MMMD.DetalleAlq 
		(DETALLE_ALQ_ALQUILER_CODIGO,
		DETALLE_ALQ_NRO_PERIODO_INI,
		DETALLE_ALQ_NRO_PERIODO_FIN,
		DETALLE_ALQ_PRECIO)
	SELECT DISTINCT 
		m.ALQUILER_CODIGO,
		m.DETALLE_ALQ_NRO_PERIODO_INI, 
		m.DETALLE_ALQ_NRO_PERIODO_FIN, 
		m.DETALLE_ALQ_PRECIO 
	FROM gd_esquema.Maestra m
	WHERE ALQUILER_CODIGO IS NOT NULL
END 
GO

CREATE PROCEDURE MMMD.Migrar_Inquilino AS
BEGIN
	INSERT INTO MMMD.Inquilino
		(INQUILINO_NOMBRE, 
		INQUILINO_APELLIDO, 
		INQUILINO_DNI, 
		INQUILINO_FECHA_REGISTRO, 
		INQUILINO_TELEFONO, 
		INQUILINO_MAIL, 
		INQUILINO_FECHA_NAC)
	SELECT DISTINCT 
		m.INQUILINO_NOMBRE, 
		m.INQUILINO_APELLIDO, 
		m.INQUILINO_DNI, 
		m.INQUILINO_FECHA_REGISTRO, 
		m.INQUILINO_TELEFONO, 
		m.INQUILINO_MAIL, 
		m.INQUILINO_FECHA_NAC
	FROM gd_esquema.Maestra m
	WHERE INQUILINO_APELLIDO IS NOT NULL
END
GO

CREATE PROCEDURE MMMD.Migrar_EstadoAlquiler AS 
BEGIN
	INSERT INTO MMMD.EstadoAlquiler
		(ESTADO_ALQUILER_NOMBRE)
	SELECT DISTINCT 
		m.ALQUILER_ESTADO 
	FROM gd_esquema.Maestra m
	WHERE ALQUILER_ESTADO IS NOT NULL
END
GO

CREATE PROCEDURE MMMD.Migrar_Alquiler AS 
BEGIN
	INSERT INTO MMMD.Alquiler 
		(ALQUILER_CODIGO,
		ALQUILER_ANUNCIO_CODIGO, 
		ALQUILER_INQUILINO_CODIGO,
		ALQUILER_CANT_PERIODOS,
		ALQUILER_FECHA_INICIO,
		ALQUILER_FECHA_FIN,
		ALQUILER_DEPOSITO, 
		ALQUILER_COMISION, 
		ALQUILER_GASTOS_AVERIGUA, 
		ALQUILER_ESTADO)
	SELECT DISTINCT 
		m.ALQUILER_CODIGO,
		m.ANUNCIO_CODIGO,
		i.INQUILINO_CODIGO,
		m.ALQUILER_CANT_PERIODOS,
		m.ALQUILER_FECHA_INICIO,
		m.ALQUILER_FECHA_FIN,
		m.ALQUILER_DEPOSITO,
		m.ALQUILER_COMISION,
		m.ALQUILER_GASTOS_AVERIGUA,
		e.ESTADO_ALQUILER_CODIGO
	FROM gd_esquema.Maestra m
	JOIN MMMD.Inquilino i ON i.INQUILINO_DNI = m.INQUILINO_DNI 
		and i.INQUILINO_APELLIDO = m.INQUILINO_APELLIDO
		and i.INQUILINO_NOMBRE = m.INQUILINO_NOMBRE
	JOIN MMMD.EstadoAlquiler e ON e.ESTADO_ALQUILER_NOMBRE = m.ALQUILER_ESTADO 
	WHERE ALQUILER_CODIGO IS NOT NULL
END
GO

EXEC MMMD.Migrar_Comprador
EXEC MMMD.Migrar_Moneda
EXEC MMMD.Migrar_MedioDePago
EXEC MMMD.Migrar_Propietario
EXEC MMMD.Migrar_Provincia
EXEC MMMD.Migrar_Localidad
EXEC MMMD.Migrar_Barrio
EXEC MMMD.Migrar_Sucursal
EXEC MMMD.Migrar_Agente
EXEC MMMD.Migrar_DetalleAlq
EXEC MMMD.Migrar_Inquilino
EXEC MMMD.Migrar_EstadoAlquiler
EXEC MMMD.Migrar_Alquiler

DROP PROCEDURE MMMD.Migrar_Comprador
DROP PROCEDURE MMMD.Migrar_Moneda
DROP PROCEDURE MMMD.Migrar_MedioDePago
DROP PROCEDURE MMMD.Migrar_Propietario
DROP PROCEDURE MMMD.Migrar_Provincia
DROP PROCEDURE MMMD.Migrar_Localidad
DROP PROCEDURE MMMD.Migrar_Barrio
DROP PROCEDURE MMMD.Migrar_Sucursal
DROP PROCEDURE MMMD.Migrar_Agente
DROP PROCEDURE MMMD.Migrar_DetalleAlq
DROP PROCEDURE MMMD.Migrar_Inquilino
DROP PROCEDURE MMMD.Migrar_EstadoAlquiler
DROP PROCEDURE MMMD.Migrar_Alquiler

----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------- CONSTRAINTS ----------------------------------------------------
----------------------------------------------------------------------------------------------------------------------

/*FK de sucursal en agente*/
ALTER TABLE [MMMD].[Agente]
ADD CONSTRAINT FK_SucursalCodigo FOREIGN KEY (AGENTE_SUCURSAL_CODIGO)
REFERENCES [MMMD].[Sucursal] (SUCURSAL_CODIGO)
GO

/*FK de localidad en sucursal*/
ALTER TABLE [MMMD].[Sucursal]
ADD CONSTRAINT FK_LocalidadCodigo FOREIGN KEY (SUCURSAL_LOCALIDAD_CODIGO)
REFERENCES [MMMD].[Localidad] (LOCALIDAD_CODIGO)
GO

/*FK de provincia en localidad*/
ALTER TABLE [MMMD].[Localidad]
ADD CONSTRAINT FK_ProvinciaCodigo FOREIGN KEY (LOCALIDAD_PROVINCIA_CODIGO)
REFERENCES [MMMD].[Provincia] (PROVINCIA_CODIGO)
GO

/*FK de localidad en barrio*/
ALTER TABLE [MMMD].[Barrio]
ADD CONSTRAINT FK_LocalidadDeBarrioCodigo FOREIGN KEY (BARRIO_LOCALIDAD_CODIGO)
REFERENCES [MMMD].[Localidad] (LOCALIDAD_CODIGO)
GO

/*Fk de tipo operacion en anuncio*/
ALTER TABLE [MMMD].[Anuncio]
ADD CONSTRAINT FK_TipoOperacionCodigo FOREIGN KEY (ANUNCIO_TIPO_OPERACION)
REFERENCES [MMMD].[TipoOperacion] (OP_CODIGO)
GO

/*Fk de moneda en anuncio*/
ALTER TABLE [MMMD].[Anuncio]
ADD CONSTRAINT FK_MonedaAnuncioCodigo FOREIGN KEY (ANUNCIO_MONEDA)
REFERENCES [MMMD].[Moneda] (MONEDA_CODIGO)
GO

/*Fk de estado anuncio en anuncio*/
ALTER TABLE [MMMD].[Anuncio]
ADD CONSTRAINT FK_EstadoCodigo FOREIGN KEY (ANUNCIO_ESTADO)
REFERENCES [MMMD].[EstadoAnuncio] (ESTADO_ANUNCIO_CODIGO)
GO

/*Fk de tipo tipo periodo en anuncio*/
ALTER TABLE [MMMD].[Anuncio]
ADD CONSTRAINT FK_TipoPeriodoCodigo FOREIGN KEY (ANUNCIO_TIPO_PERIODO)
REFERENCES [MMMD].[TipoPeriodo] (TIPO_PERIODO_CODIGO)
GO

/*Fk de agente en anuncio*/
ALTER TABLE [MMMD].[Anuncio]
ADD CONSTRAINT FK_AgenteCodigo FOREIGN KEY (ANUNCIO_AGENTE_CODIGO)
REFERENCES [MMMD].[Agente] (AGENTE_CODIGO)
GO

/*Fk de inmueble en anuncio*/
ALTER TABLE [MMMD].[Anuncio]
ADD CONSTRAINT FK_InmuebleCodigo FOREIGN KEY (ANUNCIO_INMUEBLE_CODIGO)
REFERENCES [MMMD].[Inmueble] (INMUEBLE_CODIGO)
GO

/*Fk de inmueble en CaracteristicaPorInmueble*/
ALTER TABLE [MMMD].[CaracteristicaPorInmueble]
ADD CONSTRAINT FK_InmuebleCaracteristicaCodigo FOREIGN KEY (INMUEBLE_CODIGO)
REFERENCES [MMMD].[Inmueble] (INMUEBLE_CODIGO)
GO

/*Fk de inmueble en CaracteristicaPorInmueble*/
ALTER TABLE [MMMD].[CaracteristicaPorInmueble]
ADD CONSTRAINT FK_CaracteristicaInmuebleCodigo FOREIGN KEY (CARACTERISTICA_CODIGO)
REFERENCES [MMMD].[CaracteristicaBase] (CARACTERISTICA_CODIGO)
GO

/*Fk de barrio en inmueble*/
ALTER TABLE [MMMD].[Inmueble]
ADD CONSTRAINT FK_BarrioCodigo FOREIGN KEY (INMUEBLE_BARRIO)
REFERENCES [MMMD].[Barrio] (BARRIO_CODIGO)
GO

/*Fk de tipo inmueble en inmueble*/
ALTER TABLE [MMMD].[Inmueble]
ADD CONSTRAINT FK_TipoInmuebleCodigo FOREIGN KEY (INMUEBLE_TIPO_INMUEBLE)
REFERENCES [MMMD].[TipoInmueble] (TIPOINMUEBLE_CODIGO)
GO

/*Fk de cantidad ambientes en inmueble*/
ALTER TABLE [MMMD].[Inmueble]
ADD CONSTRAINT FK_CantAmbientesCodigo FOREIGN KEY (INMUEBLE_CANT_AMBIENTES)
REFERENCES [MMMD].[CantidadAmbientes] (AMBIENTES_CODIGO)
GO

/*Fk de disposicion en inmueble*/
ALTER TABLE [MMMD].[Inmueble]
ADD CONSTRAINT FK_DisposicionCodigo FOREIGN KEY (INMUEBLE_DISPOSICION)
REFERENCES [MMMD].[DisposicionInmueble] (DISPOSICION_CODIGO)
GO

/*Fk de estado inmueble en inmueble*/
ALTER TABLE [MMMD].[Inmueble]
ADD CONSTRAINT FK_EstadoInmuebleCodigo FOREIGN KEY (INMUEBLE_ESTADO)
REFERENCES [MMMD].[EstadoInmueble] (ESTADO_INMUEBLE_CODIGO)
GO

/*Fk de propietario en inmueble*/
ALTER TABLE [MMMD].[Inmueble]
ADD CONSTRAINT FK_PropietarioCodigo FOREIGN KEY (INMUEBLE_PROPIETARIO_CODIGO)
REFERENCES [MMMD].[Propietario] (PROPIETARIO_CODIGO)
GO

/*Fk de moneda en venta*/
ALTER TABLE [MMMD].[Venta]
ADD CONSTRAINT FK_MonedaVentaCodigo FOREIGN KEY (VENTA_MONEDA)
REFERENCES [MMMD].[Moneda] (MONEDA_CODIGO)
GO

/*Fk de anuncio en venta*/
ALTER TABLE [MMMD].[Venta]
ADD CONSTRAINT FK_AnuncioVentaCodigo FOREIGN KEY (VENTA_ANUNCIO_CODIGO)
REFERENCES [MMMD].[Anuncio] (ANUNCIO_CODIGO)
GO

/*Fk de comprador en venta*/
ALTER TABLE [MMMD].[Venta]
ADD CONSTRAINT FK_CompradorCodigo FOREIGN KEY (VENTA_COMPRADOR_CODIGO)
REFERENCES [MMMD].[Comprador] (COMPRADOR_CODIGO)
GO

/*Fk de venta en pago venta*/
ALTER TABLE [MMMD].[PagoVenta]
ADD CONSTRAINT FK_VentaCodigo FOREIGN KEY (PAGO_VENTA_VENTA_CODIGO)
REFERENCES [MMMD].[Venta] (VENTA_CODIGO)
GO

/*Fk de moneda en pago venta*/
ALTER TABLE [MMMD].[PagoVenta]
ADD CONSTRAINT FK_MonedaPagoVentaCodigo FOREIGN KEY (PAGO_VENTA_MONEDA)
REFERENCES [MMMD].[Moneda] (MONEDA_CODIGO)
GO

/*Fk de medio pago en pago venta*/
ALTER TABLE [MMMD].[PagoVenta]
ADD CONSTRAINT FK_MedioPagoPagoVentaCodigo FOREIGN KEY (PAGO_VENTA_MEDIO_PAGO)
REFERENCES [MMMD].[MedioDePago] (MEDIO_PAGO_CODIGO)
GO

/*Fk de anuncio en alquiler*/
ALTER TABLE [MMMD].[Alquiler]
ADD CONSTRAINT FK_AnuncioAlquilerCodigo FOREIGN KEY (ALQUILER_ANUNCIO_CODIGO)
REFERENCES [MMMD].[Anuncio] (ANUNCIO_CODIGO)
GO

/*Fk de anuncio en alquiler*/
ALTER TABLE [MMMD].[Alquiler]
ADD CONSTRAINT FK_InquilinoCodigo FOREIGN KEY (ALQUILER_INQUILINO_CODIGO)
REFERENCES [MMMD].[Inquilino] (INQUILINO_CODIGO)
GO

/*Fk de estado alquiler en alquiler*/
ALTER TABLE [MMMD].[Alquiler]
ADD CONSTRAINT FK_EstadoAlquilerCodigo FOREIGN KEY (ALQUILER_ESTADO)
REFERENCES [MMMD].[EstadoAlquiler] (ESTADO_ALQUILER_CODIGO)
GO

/*Fk de alquiler en detalle alquiler*/
ALTER TABLE [MMMD].[DetalleAlq]
ADD CONSTRAINT FK_AlquilerDetalleCodigo FOREIGN KEY (DETALLE_ALQ_ALQUILER_CODIGO)
REFERENCES [MMMD].[Alquiler] (ALQUILER_CODIGO)
GO

/*Fk de alquiler en pago alquiler*/
ALTER TABLE [MMMD].[PagoAlquiler]
ADD CONSTRAINT FK_AlquilerPagoCodigo FOREIGN KEY (PAGO_ALQUILER_ALQUILER_CODIGO)
REFERENCES [MMMD].[Alquiler] (ALQUILER_CODIGO)
GO

/*Fk de medio de pago en pago alquiler*/
ALTER TABLE [MMMD].[PagoAlquiler]
ADD CONSTRAINT FK_MedioPagoPagoAlquilerCodigo FOREIGN KEY (PAGO_ALQUILER_MEDIO_PAGO)
REFERENCES [MMMD].[MedioDePago] (MEDIO_PAGO_CODIGO)




/*************************************************************************************************************/
/*************************************************************************************************************/
/********************************************PARA BORRAR LAS TABLAS: *****************************************/
/*************************************************************************************************************/
/*************************************************************************************************************/

/*Comandos para borrar todas las tablas (teniendo en cuenta las FKs) (tiene en cuenta si hay datos cargados?)*/
ALTER TABLE [MMMD].[Agente]
DROP CONSTRAINT FK_SucursalCodigo

ALTER TABLE [MMMD].[Sucursal]
DROP CONSTRAINT FK_LocalidadCodigo

ALTER TABLE [MMMD].[Localidad]
DROP CONSTRAINT FK_ProvinciaCodigo

ALTER TABLE [MMMD].[Barrio]
DROP CONSTRAINT FK_LocalidadDeBarrioCodigo

ALTER TABLE [MMMD].[Anuncio]
DROP CONSTRAINT FK_TipoOperacionCodigo

ALTER TABLE [MMMD].[Anuncio]
DROP CONSTRAINT FK_MonedaAnuncioCodigo

ALTER TABLE [MMMD].[Anuncio]
DROP CONSTRAINT FK_EstadoCodigo

ALTER TABLE [MMMD].[Anuncio]
DROP CONSTRAINT FK_TipoPeriodoCodigo

ALTER TABLE [MMMD].[Anuncio]
DROP CONSTRAINT FK_AgenteCodigo

ALTER TABLE [MMMD].[Anuncio]
DROP CONSTRAINT FK_InmuebleCodigo

ALTER TABLE [MMMD].[CaracteristicaPorInmueble]
DROP CONSTRAINT FK_InmuebleCaracteristicaCodigo

ALTER TABLE [MMMD].[CaracteristicaPorInmueble]
DROP CONSTRAINT FK_CaracteristicaInmuebleCodigo

ALTER TABLE [MMMD].[Inmueble]
DROP CONSTRAINT FK_BarrioCodigo

ALTER TABLE [MMMD].[Inmueble]
DROP CONSTRAINT FK_TipoInmuebleCodigo

ALTER TABLE [MMMD].[Inmueble]
DROP CONSTRAINT FK_CantAmbientesCodigo

ALTER TABLE [MMMD].[Inmueble]
DROP CONSTRAINT FK_DisposicionCodigo

ALTER TABLE [MMMD].[Inmueble]
DROP CONSTRAINT FK_EstadoInmuebleCodigo

ALTER TABLE [MMMD].[Inmueble]
DROP CONSTRAINT FK_PropietarioCodigo

ALTER TABLE [MMMD].[Venta]
DROP CONSTRAINT FK_MonedaVentaCodigo

ALTER TABLE [MMMD].[Venta]
DROP CONSTRAINT FK_AnuncioVentaCodigo

ALTER TABLE [MMMD].[Venta]
DROP CONSTRAINT FK_CompradorCodigo

ALTER TABLE [MMMD].[PagoVenta]
DROP CONSTRAINT FK_VentaCodigo

ALTER TABLE [MMMD].[PagoVenta]
DROP CONSTRAINT FK_MonedaPagoVentaCodigo

ALTER TABLE [MMMD].[PagoVenta]
DROP CONSTRAINT FK_MedioPagoPagoVentaCodigo

ALTER TABLE [MMMD].[Alquiler]
DROP CONSTRAINT FK_AnuncioAlquilerCodigo

ALTER TABLE [MMMD].[Alquiler]
DROP CONSTRAINT FK_InquilinoCodigo

ALTER TABLE [MMMD].[Alquiler]
DROP CONSTRAINT FK_EstadoAlquilerCodigo

ALTER TABLE [MMMD].[DetalleAlq]
DROP CONSTRAINT FK_AlquilerDetalleCodigo

ALTER TABLE [MMMD].[PagoAlquiler]
DROP CONSTRAINT FK_AlquilerPagoCodigo

ALTER TABLE [MMMD].[PagoAlquiler]
DROP CONSTRAINT FK_MedioPagoPagoAlquilerCodigo


DROP TABLE [MMMD].[Agente]
DROP TABLE [MMMD].[Sucursal]
DROP TABLE [MMMD].[Localidad]
DROP TABLE [MMMD].[Provincia]
DROP TABLE [MMMD].[Barrio]
DROP TABLE [MMMD].[Anuncio]
DROP TABLE [MMMD].[TipoOperacion]
DROP TABLE [MMMD].[Moneda]
DROP TABLE [MMMD].[EstadoAnuncio]
DROP TABLE [MMMD].[TipoPeriodo]
DROP TABLE [MMMD].[Inmueble]
DROP TABLE [MMMD].[CaracteristicaBase]
DROP TABLE [MMMD].[CaracteristicaPorInmueble]
DROP TABLE [MMMD].[TipoInmueble]
DROP TABLE [MMMD].[CantidadAmbientes]
DROP TABLE [MMMD].[DisposicionInmueble]
DROP TABLE [MMMD].[EstadoInmueble]
DROP TABLE [MMMD].[Propietario]
DROP TABLE [MMMD].[Venta]
DROP TABLE [MMMD].[Comprador]
DROP TABLE [MMMD].[PagoVenta]
DROP TABLE [MMMD].[MedioDePago]
DROP TABLE [MMMD].[Alquiler]
DROP TABLE [MMMD].[Inquilino]
DROP TABLE [MMMD].[EstadoAlquiler]
DROP TABLE [MMMD].[DetalleAlq]
DROP TABLE [MMMD].[PagoAlquiler]